---
- name: GRAB F5 FACTS
  hosts: lb
  connection: local
  gather_facts: no

  # - hosts: all
  #   vars_prompt:
  #     - name: ansible_host
  #       prompt: "Enter Host"
  #       private: no
  #     - name: ansible_user
  #       prompt: "Enter User"
  #       private: no
  #     - name: ansible_ssh_pass
  #       prompt: "Enter Password"
  #       private: yes

  tasks:
    - name: Set a fact named 'provider' with BIG-IP login information
      set_fact:
        provider:
          server: "{{ansible_host}}"
          user: "{{ansible_user}}"
          password: "{{ansible_ssh_pass}}"
          server_port: 443
          validate_certs: no

    - name: COLLECT BIG-IP FACTS
      bigip_device_info:
        provider: "{{provider}}"
        gather_subset:
          - ltm-pools
          - virtual-servers
      register: device_facts

    - name: Copy output to file
      copy:
        content: "{{ device_facts }}"
        dest: "facts.json"
